default:
 image: node:15.10.0-alpine3.13

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
    - 'npm install'

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
      - node_modules/

stages:
    - validate
    - test


code_quality:
 stage: validate
 script:
   - 'npm run ng lint'

Test:
  stage: test
  script:
    - npm run ng test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  tags:
    - docker


