default:
 image: node:15.10.0-alpine3.13
 before_script:
     - 'npm install'

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
      - node_modules/

stages:
    - validate
    - test


code_quality:
 stage: validate
 script:
   - 'npm run ng lint'

Test:
  stage: test
  script:
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
