default:
 image: node:15.10.0-alpine3.13
 before_script:
     - 'npm install'

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
      - node_modules/

stages:
    - validate
    - test


code_quality:
 stage: validate
 script:
   - 'npm run ng lint'

test_a:
  stage: test
  script:
    - 'npm run ng e2e'
